version: "3"
services:
  db:
    image: mysql
    restart: always
    ports:
    -  "3306:3306"
    expose:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: auth
      MYSQL_USER: root
      MYSQL_PASSWORD: password
  nest:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    links:
      - db:mysql
    command: ["./wait-for-it.sh", "mysql:3306"]   

     